"""Editable periodic segmentation baseline, independent of business skills."""
from copy import deepcopy

_TEMPLATE = {'schema_version': 3,
 'name': 'periodic_segmentation_baseline',
 'nodes': [{'id': 'denoised',
            'operator': 'gaussian_denoise',
            'inputs': {'image': '$image'},
            'params': {'sigma': 0.8}},
           {'id': 'period',
            'operator': 'period_estimation',
            'inputs': {'image': 'denoised'},
            'params': {'axis': 'auto'}},
           {'id': 'background',
            'operator': 'build_periodic_background',
            'inputs': {'image': 'denoised', 'period': 'period'},
            'params': {'harmonic': 'auto'}},
           {'id': 'residual',
            'operator': 'subtract_periodic_background',
            'inputs': {'image': 'denoised', 'background': 'background'},
            'params': {'mode': 'absolute'}},
           {'id': 'valid_region',
            'operator': 'build_periodic_valid_mask',
            'inputs': {'image': '$image', 'period': 'period'},
            'params': {'border_px': 1}},
           {'id': 'threshold_mask',
            'operator': 'threshold_residual',
            'inputs': {'image': 'residual', 'valid_mask': 'valid_region'},
            'params': {'method': 'percentile', 'percentile': 97.0}},
           {'id': 'constrained_mask',
            'operator': 'apply_mask_constraint',
            'inputs': {'mask': 'threshold_mask', 'valid_mask': 'valid_region'},
            'params': {}},
           {'id': 'opened_mask',
            'operator': 'morphology',
            'inputs': {'mask': 'constrained_mask'},
            'params': {'method': 'open', 'radius': 1}},
           {'id': 'closed_mask',
            'operator': 'morphology',
            'inputs': {'mask': 'opened_mask'},
            'params': {'method': 'close', 'radius': 3}},
           {'id': 'filled_mask', 'operator': 'fill_holes', 'inputs': {'mask': 'closed_mask'}, 'params': {}},
           {'id': 'final_mask',
            'operator': 'filter_components',
            'inputs': {'mask': 'filled_mask'},
            'params': {'min_area': 20, 'min_aspect_ratio': 0.2, 'max_aspect_ratio': 5.0}},
           {'id': 'contours',
            'operator': 'extract_contours',
            'inputs': {'mask': 'final_mask'},
            'params': {}}],
 'outputs': {'mask': 'final_mask', 'contours': 'contours'}}

def periodic_segmentation_template():
    return deepcopy(_TEMPLATE)
